"""cart model change

Revision ID: 3d53072e460b
Revises: f2e6b564674a
Create Date: 2026-09-12 17:01:10.023997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d53072e460b'
down_revision: Union[str, Sequence[str], None] = 'f2e6b564674a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('cart_status', sa.Enum('SUCCESSFUL', 'UNSUCCESSFUL', 'CANCELLED', name='cartstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'cart_status')
    # ### end Alembic commands ###
