"""update restaurant model

Revision ID: 6adf43c625ab
Revises: 3d53072e460b
Create Date: 2026-09-16 16:49:06.883563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6adf43c625ab'
down_revision: Union[str, Sequence[str], None] = '3d53072e460b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('phone', sa.String(length=15), nullable=False))
    op.add_column('restaurant', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('restaurant', sa.Column('is_open', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'is_open')
    op.drop_column('restaurant', 'address')
    op.drop_column('restaurant', 'phone')
    # ### end Alembic commands ###
