"""order table correction

Revision ID: 6d4c6997705c
Revises: acb78e8fa480
Create Date: 2026-08-10 17:40:23.006436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d4c6997705c'
down_revision: Union[str, Sequence[str], None] = 'acb78e8fa480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.alter_column('order', 'status',
               existing_type=mysql.ENUM('PENDING', 'CONFIMED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED'),
               nullable=False)
    op.create_index(op.f('ix_order_restaurant_id'), 'order', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'order', 'restaurant', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_index(op.f('ix_order_restaurant_id'), table_name='order')
    op.alter_column('order', 'status',
               existing_type=mysql.ENUM('PENDING', 'CONFIMED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED'),
               nullable=True)
    op.drop_column('order', 'restaurant_id')
    # ### end Alembic commands ###
