"""alembic init

Revision ID: 81ec532b6d15
Revises: 
Create Date: 2026-08-04 17:04:29.484402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '81ec532b6d15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('food', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.add_column('food', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_food_restaurant_id'), 'food', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'food', 'restaurant', ['restaurant_id'], ['id'])
   
    op.alter_column('restaurant', 'rating',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('restaurant', 'rating',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('food', sa.Column('Food_type', mysql.ENUM('VEG', 'NONVEG'), nullable=False))
    op.drop_constraint(None, 'food', type_='foreignkey')
    op.drop_index(op.f('ix_food_restaurant_id'), table_name='food')
    op.drop_column('food', 'is_available')
    op.drop_column('food', 'restaurant_id')
    op.drop_column('food', 'food_type')
    # ### end Alembic commands ###
