"""change cart_model in  alembic

Revision ID: f7017962cdc7
Revises: 4d36789e344e
Create Date: 2026-08-06 17:58:40.003003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7017962cdc7'
down_revision: Union[str, Sequence[str], None] = '4d36789e344e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('total_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'total_price')
    # ### end Alembic commands ###
